### ISSUE TITLE
X-UI-Collections-Bundle - "Update" doesn't work anymore

### ISSUE THREAD

**Issue by qfl1ck32** [bluelibs/bluelibs#231] opened 2022-03-03 08:35 UTC
On a freshly-generated project, you can go to the admin panel and try to update a document from any collection. You'll receive the following error:

```
GraphQLError: Syntax Error: Expected Name, found "$".
    at syntaxError (syntaxError.mjs:8:1)
    at Parser.expectToken (parser.mjs:1397:22)
    at Parser.parseName (parser.mjs:82:1)
    at Parser.parseField (parser.mjs:279:1)
    at Parser.parseSelection (parser.mjs:268:38)
    at Parser.many (parser.mjs:1507:1)
    at Parser.parseSelectionSet (parser.mjs:255:1)
    at Parser.parseField (parser.mjs:296:48)
    at Parser.parseSelection (parser.mjs:268:38)
    at Parser.many (parser.mjs:1507:1)
```

The request is not sent, meaning it's a problem when formatting the query on the front-end.

**Comment by Fen747** [comment] 2022-03-03 09:47
Related to #213 .

I've introduced that bug when my PR about auto-refetch fields got merged.

The problem is that the auto-refetch reads the fields you mutate to automatically refetch them and update the cache. Problem : it's not intended to work with mongo modifiers.

Two solution :
- When using mongo modifiers, we simply don't auto-refetch, it should be to be highlighted as a big warning in the documention, but would result in a weird inconsistency (but it's quick to fix)
- Best : we parse the mongo modifier to build the refetch body. I think that's possible as, in server side collection BeforeUpdateEvent, we have `fields.top` and `fields.all`, meaning we surely already have that kind of parsing lying somewhere in the code.

**Closed** 2022-03-04 06:57 UTC
